FROM node:19.6.0
WORKDIR /
COPY ./package.json /package.json
COPY ./public /public
COPY ./src /src
RUN yarn config set network-timeout 600000 -g
RUN yarn install
EXPOSE 3000
CMD ["yarn","client"]